// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6-hK0MHzArIrJVhlm6DXehuRVYqgbEig',
    appId: '1:171205810996:web:b4857c8d019de5012ee361',
    messagingSenderId: '171205810996',
    projectId: 'voycontigo-1a327',
    authDomain: 'voycontigo-1a327.firebaseapp.com',
    storageBucket: 'voycontigo-1a327.firebasestorage.app',
    measurementId: 'G-N0WSTRDPE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqLGlv29s3ZZBv5_YtEOaH9kkB8zGXLP4',
    appId: '1:171205810996:android:49acd09e9c55fc3a2ee361',
    messagingSenderId: '171205810996',
    projectId: 'voycontigo-1a327',
    storageBucket: 'voycontigo-1a327.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8hLUKxqt36Dluif7qc21MmXFt8QoaXCY',
    appId: '1:171205810996:ios:ff4a0a5c42ca46222ee361',
    messagingSenderId: '171205810996',
    projectId: 'voycontigo-1a327',
    storageBucket: 'voycontigo-1a327.firebasestorage.app',
    iosClientId: '171205810996-7hmkgts341pidv701u11rero7ovuice8.apps.googleusercontent.com',
    iosBundleId: 'com.voycontigo.voycontigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8hLUKxqt36Dluif7qc21MmXFt8QoaXCY',
    appId: '1:171205810996:ios:ff4a0a5c42ca46222ee361',
    messagingSenderId: '171205810996',
    projectId: 'voycontigo-1a327',
    storageBucket: 'voycontigo-1a327.firebasestorage.app',
    iosClientId: '171205810996-7hmkgts341pidv701u11rero7ovuice8.apps.googleusercontent.com',
    iosBundleId: 'com.voycontigo.voycontigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVI78zLCknByBMuMQPM9gqL8e2ZtFmuqY',
    appId: '1:171205810996:web:d439f479bf0053882ee361',
    messagingSenderId: '171205810996',
    projectId: 'voycontigo-1a327',
    authDomain: 'voycontigo-1a327.firebaseapp.com',
    storageBucket: 'voycontigo-1a327.firebasestorage.app',
    measurementId: 'G-ZQQY2HGV00',
  );
}
